### ISSUE TITLE
model_path

### ISSUE THREAD

**Issue by Hannah1746** [bioinfomaticsCSU/deepsignal#11]
So when I try to run:
deepsignal call_mods --input_path fast5s.al.CpG.signal_features.17bases.rawsignals_360.tsv --model_path model.CpG.R9.4_1D.human_hx1.bn17.sn360/bn_17.sn_360.epoch_7.ckpt --result_file fast5s.al.CpG.call_mods.tsv --nproc 10 --is_gpu no
the model path is wrong. From the trainer I downloaded form:
http://bioinformatics.csu.edu.cn/resources/softs/nipeng/DeepSignal/index.html
I get a file named:
model.CpG.R9.4_1D.human_hx1.bn17.sn360
but when I go into the file there is no file named:
bn_17.sn_360.epoch_7.ckpt
witch of the files should I be using for the second half of the model_path?
![Screenshot from 2019-05-30 11-49-58](https://user-images.githubusercontent.com/50594446/58645345-3033fd00-82d1-11e9-911b-dd81978332eb.png)

**Comment by PengNi** [comment]
Hi @Hannah1746 ,

We've updated a new and more stable model, which can be downloaded from [google drive](https://drive.google.com/open?id=1zkK8Q1gyfviWWnXUBMcIwEDw3SocJg7P) or [clemson](https://people.cs.clemson.edu/~luofeng/deepsignal/).
We will also update the model in [http://bioinformatics.csu.edu.cn/resources/softs/nipeng/DeepSignal/index.html](http://bioinformatics.csu.edu.cn/resources/softs/nipeng/DeepSignal/index.html) soon. Sorry for making you confused.

Best,
Peng

**Comment by yaeba** [comment]
Hi @PengNi ,

I have downloaded the latest trained model from [google drive](https://drive.google.com/drive/folders/1zkK8Q1gyfviWWnXUBMcIwEDw3SocJg7P) and [bioinformatics](http://bioinformatics.csu.edu.cn/resources/softs/nipeng/DeepSignal/index.html) but there is still no sign of a .ckpt file usable for calling methylation. 
![Screen Shot 2019-07-11 at 3 59 07 pm](https://user-images.githubusercontent.com/43712735/61025714-d86ed280-a3f4-11e9-97ec-48f139ce7cba.png)

**Comment by PengNi** [comment]
Hi @yaeba , 

Sorry for making you confused. `*.ckpt` actually is prefix of those file names. It is a tensorflow feature. The prefix is used to indicate those files in the folder, all together as a model (a bunch of parameters).
So you can use `/path/to/model/bn_17.sn_360.epoch_7.ckpt` as the value of `--model_path` . 

Best,
Peng

**Comment by yaeba** [comment]
Thanks for clearing that up for me @PengNi
