### ISSUE TITLE
How to get my files to basecall

### ISSUE THREAD

**Issue by Hannah1746** [bioinfomaticsCSU/deepsignal#12]
I am trying to get my files in the right format to run deepsignal and I am having a lot of troubles. My fast5 files need to be basecalled from my fastq files. In the instructions it says "If the basecall results are saved as fastq, run the [*tombo proprecess annotate_raw_with_fastqs*]". I have done that but I am getting this error:
![Not working](https://user-images.githubusercontent.com/50594446/58888829-ff2f4000-86b5-11e9-87da-4f20145f23b8.png)
 Help?

**Comment by PengNi** [comment]
Hi @Hannah1746 ,

the arg value of _--fastq-filenames_ seems not right. One possible solution is to _cat_ all fastqs in directory to one fastq file using the following command: 
```bash
cat Gill_pratice_fastq/* > Gill_pratice_fastq.all.fastq
```
then use  _Gill_pratice_fastq.all.fastq_ as the value of _--fastq-filenames_ .

**Comment by Hannah1746** [comment]
I was doing that originally and it gave me the same error.

**Comment by PengNi** [comment]
Hi @Hannah1746 ,

It is a little bit difficult for us to guess the problem without having the data. However, the picture you uploaded indicates that in your fast5 directory there are only **6** fast5 files. This is abnormal and could be a possible reson. May be either your fast5 directory is incorrect or the fast5 files in it are multi-fast5-format.

So could you check the fast5 directory and tell me what you see (how many fast5 files in it, the size of one fast5 file)?

Best,
Peng

**Comment by Hannah1746** [comment]
This is my Fast5 and Fastq. There is only 6 of them because I am just doing a test run with a small amount of data to make it work before I used my 1.4 terabits of data. I also shared these files with you on google drive.
 
![Screenshot from 2019-06-06 12-02-52](https://user-images.githubusercontent.com/50594446/59048241-6b937600-8853-11e9-953a-4686adbfff92.png)
![Screenshot from 2019-06-06 12-02-45](https://user-images.githubusercontent.com/50594446/59048242-6b937600-8853-11e9-9907-d1c27e3a4f52.png)

**Comment by PengNi** [comment]
Hi @Hannah1746 ,

We checked the fast5 files you shared, the fast5 files are indeed multi-fast5-format. According to [tombo](https://github.com/nanoporetech/tombo), we now should use _multi_to_single_fast5_ in [ont_fast5_api](https://github.com/nanoporetech/ont_fast5_api) to convert them first.
![QQ截图20190607090422](https://user-images.githubusercontent.com/4242364/59075473-43635000-8903-11e9-893b-c11ef908019f.png)

Best, 
Peng
