### ISSUE TITLE
Add warning or more test when deleting content of model directory

### ISSUE THREAD

**Issue by pterzian** [bioinfomaticsCSU/deepsignal#14]
Hi there,

I'm opening this issue because I think [these lines](https://github.com/bioinfomaticsCSU/deepsignal/blob/45af3ab493ca3d4f976e1dd0c6d911543277c8e5/deepsignal/train_model.py#L46-L55) in the `train_model.py` file might be dangerous. 

The first time I used this script I wanted to save the custom model at the root of my deepsignal working directory so I set `--model_dir` value to `.` and it did delete everything in my current folder without any explanation (hopefully I recovered everything).

Best,
Paul

**Comment by PengNi** [comment]
Hi Paul,

It is dangerous indeed. Sorry we didn't think of it before and make you in unnecessary trouble. We will patch it ASAP.

Best, 
Peng

**Comment by PengNi** [comment]
See [382585e](https://github.com/bioinfomaticsCSU/deepsignal/commit/382585edd99408eabf08c5528ce1b177b8a14013).
