### ISSUE TITLE
Meaning of cent_signals

### ISSUE THREAD

**Issue by cednotsed** [bioinfomaticsCSU/deepsignal#16]
Hi,

May I ask what does cent_signal mean exactly? 

Also, with reference to your extract features module, how was the signal mean, std and signal len calculated for each base in each k-mer after resquiggle was performed? I noticed that the TSV file output of the extract features module contains a list of comma separated values for the signal mean, std, signal len columns.

**Comment by PengNi** [comment]
Hi, 

`cent_signals` are the central _m_ (default 360) signals from the signals of  each k-mer. 

After re-squiggle, each base will get it's corresponding (usually 5-30) signals. Then we calculate the mean, std, length of the signals of each base.

You can check out our published manuscript ([btz276](https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btz276/5474907)) for more information.

Best,
Peng
