### ISSUE TITLE
Split extracted_features file and run methylation calling

### ISSUE THREAD

**Issue by vahidAK** [bioinfomaticsCSU/deepsignal#20]
Hi @PengNi ,
I was wondering if is it possible to split extracted_features file and then performing methylation calling on each file separately?

Thanks,
Vahid.

**Comment by PengNi** [comment]
Hi @vahidAK ,

I'm not sure the reason you want to do so. Is that because the generated extracted_features file too big? The modifications can also be called from the fast5 files directly, which skips the extract_feature step.

Or there is another reason?

Best,
Peng

**Comment by vahidAK** [comment]
Thanks for your response, no I have different machines to run and I want to split the file and separate the job between them to be faster.

**Comment by PengNi** [comment]
Hi @vahidAK ,

Sorry we didn't consider this case before. We may update deepsignal once we get time for this case. 

However, you can split the file manually. The extracted_features file is a  text file. Each line in the file is a sample to be tested and is independent to other lines. 

Best,
Peng

**Comment by vahidAK** [comment]
Thanks, @PengNi

**Comment by PengNi** [comment]
see commit [89b58d1](https://github.com/bioinfomaticsCSU/deepsignal/commit/89b58d176453e6ec64da15f3572438327a88c299).
