### ISSUE TITLE
How to calculate accuracy and other metrics by evaluate_mods_call.py?

### ISSUE THREAD

**Issue by vahidAK** [bioinfomaticsCSU/deepsignal#23]
Hi @PengNi ,

I would be very grateful if you could help me on how to calculate accuracy.
I know have bisulfite data and methylation_frequency data from DeepSignal. How should I use your script to calculate accuracy?
It says I need two result files, one contains calls for methylated sites, another contains calls for
unmethylated sites. What is calls for methylated sites (is it methylation frequency file?) and what is calls for unmethylated sites?

Many thanks,
Vahid.

**Comment by PengNi** [comment]
@vahidAK , to calculate accuracy, I choose high-confidence (totally methylated/unmethylated) sites at first. Then I extract modification calls of the standard sites from the call_mods file to two seperate files.

**Comment by vahidAK** [comment]
Thanks a lot , @PengNi
