### ISSUE TITLE
It would be very nice if you could add cuda option to DeepSignal

### ISSUE THREAD

**Issue by vahidAK** [bioinfomaticsCSU/deepsignal#24]
Hi @PengNi ,
One thing I noticed that could be a good enhancement to deepsignal is cuda option. 
We have 7 GPUs and when I run deppsignal on gpu server it distributes job on all gpus and just uses part of their ram and processing power, so it would be very useful if you could add options to select the gpu number and amount of threads and ram for each gpu in deepsignal.

Thanks,
Vahid

**Comment by PengNi** [comment]
Hi @vahidAK , you can try add `CUDA_VISIBLE_DEVICES=0` before the `deepsignal` command, like `CUDA_VISIBLE_DEVICES=0 deepsignal call_mods ...` (0 is the GPU number). That's what we did in our experiments.

**Comment by vahidAK** [comment]
Hi @PengNi 
Great! thanks a lot
