### ISSUE TITLE
Your paper circle plot

### ISSUE THREAD

**Issue by vahidAK** [bioinfomaticsCSU/deepsignal#26]
Hi @PengNi ,
Sorry for this silly question, but I was wondering how you made that circle plot in your paper.
As you mentioned in the paper you binned genome in 1mb regions, did you also binned methylation frequency file and mean/sum methylation frequencies in those 1mb regions?

I am trying to reproduce a similar plot but mine is completely different.
Thanks,
Vahid.

**Comment by PengNi** [comment]
Hi @vahidAK , 

In my circos plot, I just use the number of CpGs (which deepsignal can detect but BS cannot detect, coverage>=5) in each binned region to plot a histogram. I didn't use the methylation frequency file. The plot is to show that using nanopore reads can detect more CpGs than bisulfite sequencing. 

Best,
Peng
