### ISSUE TITLE
Non-CpG methylation calling

### ISSUE THREAD

**Issue by vahidAK** [bioinfomaticsCSU/deepsignal#27]
Hi @PengNi 
I was wondering that deepsignal does have a model for non-CpG methylation cytosine calling in human?

Best,
Vahid

**Comment by PengNi** [comment]
@vahidAK , we don't have CHG or CHH model for human in deepsignal. Based on our experiments, CHG/CHH are rarely occurred in human. We can't generate enough training data.

**Comment by vahidAK** [comment]
Thanks @PengNi
