### ISSUE TITLE
Don't import tensorflow when extracting features

### ISSUE THREAD

**Issue by snajder-r** [bioinfomaticsCSU/deepsignal#29]
Hi!

This would just be a small quality-of-life improvement. Currently, deepsignal.py imports train_model and call_mods even when I am actually calling extract. train_model and call_mods then want to import tensorflow, and tensorflow depends on libcuda, none of which is required by the feature extraction command.

This can be a bit problematic in a compute cluster environment where you have dedicated GPU nodes (which have libcuda) and non-GPU nodes (which don't have libcuda). It forces me to run the feature extraction on a GPU node, despite it not using a GPU, thus reserving a valuable resource I'm not actually using.

Thanks a lot!

**Comment by PengNi** [comment]
Hi @snajder-r , this is truly a problem. please checkout the latest version of deepsignal after commit [0973161](https://github.com/bioinfomaticsCSU/deepsignal/commit/0973161271cf885a661852ad047519c0bdc26a76), see if it works.

Best,
Peng
