### ISSUE TITLE
How long does it take to finish 30X human data?

### ISSUE THREAD

**Issue by hd00ljy** [bioinfomaticsCSU/deepsignal#30]
Hi,

  I want to know how long does it take to finish methylation calling of 30X 1D human WGS data on 4 Titan V you used.

  More specifically I want to know how you get the running time in table S3 of your paper

  In table S3, for 30X NA12878 data testing, you wrote that it takes 7366.1min, which corresponds to about 5days.

  Does it mean that it takes 5 days even with 4 Titan V GPUs?

Jinyoung

**Comment by PengNi** [comment]
We used one GPU to test time cost of deepsignal. If using 4 GPUs, it may be 4 times faster.

**Comment by hd00ljy** [comment]
So it takes ~1 day for 4 GPUs?

**Comment by PengNi** [comment]
Yes, the deepsignal call_mods step costs ~1 day for 4 GPUs in our experiments.

**Comment by hd00ljy** [comment]
Thank you!

One last question.

Was the data on the SSD storage or HDD when you measured the time?



I should've organized questions in one post. Sorry for bothering you.

**Comment by PengNi** [comment]
that's all right. We used HDD storage.

**Comment by hd00ljy** [comment]
Thank you very much
