### ISSUE TITLE
Model training, feature extraction error.

### ISSUE THREAD

**Issue by vahidAK** [bioinfomaticsCSU/deepsignal#32]
Hi @PengNi ,

I am trying to use DeepSignal to train a model.
I found the zero-based position of CpGs that are modified or not. Then I used these position files to extract features to train a model on. But, when I used the extract module it does not extract any features?

Here is my command:
deepsignal extract -i fast5s/ --reference_path hg38.fa --methy_label 1 --positions position.tsv -o extracted_featur.tsv

and here is the header of my position file:
1       3287543                                                                                                                                                             1       3287547                                                                                                                                                             1       3287551                                                                                                                                                             1       3287555                                                                                                                                                             1       3287559                                                                                                                                                             1       3287563                                                                                                                                                             1       3287567                                                                                                                                                             1       3287571                                                                                                                                                             1       3287575                                                                                                                                                             1       3287579

My position file does not have a header.

However, when I do not give the position option to the command it extracts the features.

Thanks,
Vahid.

**Comment by PengNi** [comment]
Hi @vahidAK ,

The position file must be in the format of `1 3287543 +` or `1 3287543 -`, with a third column (+/-) indicates the strand of the position (in forward or backward strand). And the delimiter is `\t`.

Best,
Peng
