### ISSUE TITLE
Installation Issue 

### ISSUE THREAD

**Issue by ckhithesh** [bioinfomaticsCSU/deepsignal#33]
Dear Team,
I am facing problem with installing deepsignal. 
Tensorflow 1.8.0 is not getting installed properly.
Please share a link where I can download tensorflow=1.8.0

![Tensorflow_installation_error](https://user-images.githubusercontent.com/32487963/69498761-834ddc00-0f11-11ea-90ac-c71f1900801e.png)

**Comment by PengNi** [comment]
Hi @ckhithesh ,

Thanks for your interest. Please use our latest version from github. In our test, a version of tensorflow/tensorflow-gpu<=1.13.1 will work.

Best,
Peng

**Comment by ckhithesh** [comment]
Dear Peng,
After installation of tensorflow v1.13.1. Deepsignal has installation issues. I have mentioned in txt files below. 
[deepsignal_installation_with_python2.7.txt](https://github.com/bioinfomaticsCSU/deepsignal/files/3888324/deepsignal_installation_with_python2.7.txt)
[deepsignal_installation_with_python3.7.txt](https://github.com/bioinfomaticsCSU/deepsignal/files/3888325/deepsignal_installation_with_python3.7.txt)

Regards
Hithesh

**Comment by PengNi** [comment]
Dear @ckhithesh , please download the latest version of deepsignal and try to install it again:
```sh
git clone https://github.com/bioinfomaticsCSU/deepsignal.git
cd deepsignal
python setup.py install
```
I updated the install requirements yesterday. BTW, python2 is not supported.

Best,
Peng

**Comment by ckhithesh** [comment]
Dear Team,
Thank you for your support. Deepsignal installed successfully. But in the step of call modifications I'm getting few errors.

[Cal_modification_error.txt](https://github.com/bioinfomaticsCSU/deepsignal/files/3893601/Cal_modification_error.txt)

Regards 
Hithesh

**Comment by PengNi** [comment]
Hi @ckhithesh , I installed tensorflow1.13.1 in an virtual environment to run deepsignal, it shows no problem.

Here are the packages in my environment:
![QQ截图20191127111604](https://user-images.githubusercontent.com/4242364/69690634-74307f00-1107-11ea-853e-421f805d51e6.png)

I guess the issue may be caused by the improper versions of some packages like `tensorflow-estimator` or `tensorboard`? 

Best,
Peng
