### ISSUE TITLE
Feature extraction

### ISSUE THREAD

**Issue by vahidAK** [bioinfomaticsCSU/deepsignal#35]
Hi @PengNi 
Do you consider mismatches with the reference during feature extraction? 
As you know, the error rate of the nanopore is high and there may be many cytosines that actually might not be C when compare it to reference. I was wondering that deepsignal extracts features for cytosines that are called C from nanopore and also are C in the ref?

Thanks,
Vahid.

**Comment by PengNi** [comment]
@vahidAK , we don't consider mismatches. We use Tombo for the resquiggle, which mapping the raw signals to the genome reference, after the read-genome alignment.
