### ISSUE TITLE
download problems 

### ISSUE THREAD

**Issue by lqsae** [bioinfomaticsCSU/deepsignal#36]
I can't download the  model.CpG.R9.4_1D.human_hx1.bn17.sn360.tar.gz,
the problem is (the Forbidden You don't have permission to access /~luofeng/deepsignal/model.CpG.R9.4_1D.human_hx1.bn17.sn360.tar.gz on this server.)
can youhelp me?

**Comment by PengNi** [comment]
@lqsae , can you access google drive?

**Comment by lqsae** [comment]
Thank you for your reply, i can't acces  google drive. Is there any other way to download？


| |
刘青山
|
|
18637315793@163.com
|
签名由网易邮箱大师定制
On 12/12/2019 16:01，Peng Ni<notifications@github.com> wrote：

@lqsae , can you access google drive?

**Comment by PengNi** [comment]
@lqsae , I uploaded the model to BaiduYun, please check the following URL: https://pan.baidu.com/s/17ZQitBbrB_F3mz6R6yHkeA 
提取码：3ni4 

Best, 
Peng

**Comment by lqsae** [comment]
tank you


| |
刘青山
|
|
18637315793@163.com
|
签名由网易邮箱大师定制
On 12/12/2019 16:30，Peng Ni<notifications@github.com> wrote：

@lqsae , I uploaded the model to BaiduYun, please check the following URL: https://pan.baidu.com/s/17ZQitBbrB_F3mz6R6yHkeA
提取码：3ni4

Best,
Peng
