### ISSUE TITLE
insertion methylation level

### ISSUE THREAD

**Issue by Yeeok** [bioinfomaticsCSU/deepsignal#39]
Hi,
Is there any way to detect DNA modifications of insertions (one type of SVs) by using deepsignal ?
Or only DNA modification within reference genome regions can be detected?

Thank you.

Yeeok Kang -

**Comment by PengNi** [comment]
Hi @Yeeok ,

Thanks for your interest. Currently deepsignal doesn't support detecting DNA modifications of insertions. We only focus on base modifications in reference genome regions now.

Best,
Peng
