### ISSUE TITLE
HX1 Data availability

### ISSUE THREAD

**Issue by vahidAK** [bioinfomaticsCSU/deepsignal#42]
Hi @PengNi ,
I was wondering if your HX1 nanopore sequencing data is available somewhere?
I could not find the link to data from the paper.

Thanks,
Vahid.

**Comment by PengNi** [comment]
Hi @vahidAK , 

We did not upload HX1 data ourself. Please check out [https://hx1.wglab.org/](https://hx1.wglab.org/) to access the data.

Best, 
Peng

**Comment by vahidAK** [comment]
Thanks @PengNi ,
I checked the link but I could not find your WGA ~5x data? it only has native hx1 data

**Comment by PengNi** [comment]
Hi Vahid, sorry that the WGA data haven't been uploaded yet. If you want some negative samples to do some experiments, I suggest that you select negative samples based on bisulfite sequencing data. Actually we also used part of negative samples choosen from native reads based on bisulfite sequencing in our experiments, it should have no big difference for the result.

Best, 
Peng

**Comment by vahidAK** [comment]
Thanks @PengNi ,
Is there any chance that you will upload that data as well?
Thanks.

**Comment by PengNi** [comment]
@vahidAK, I'll see if I can get the permission and upload the data. I can't do it now because I'm not at school. I'll be at school next month maybe. Once I upload the data, I'll give you the link. 

Best, 
Peng

**Comment by vahidAK** [comment]
I really appreciate it, @PengNi ,
Thanks a lot

**Comment by PengNi** [comment]
Hi @vahidAK , Sorry for the delay. I just asked my advisor, I am sorry that we don't own the data. If you still want to use the data, you can concact [Mr Wang at Grandomics](https://www.grandomics.com/en/company/ourteam/). 

If you can't find his email, you can email me first (543943952@qq.com).

Best,
Peng
