### ISSUE TITLE
Results of extract features step

### ISSUE THREAD

**Issue by zcWang0591** [bioinfomaticsCSU/deepsignal#49]
Hi, I am now trying to reproduce your example.  According to your guidance, at the extract features step, the output file will be a tab-delimited text file. And I am confused with two terms of this file, "strand" and "read_strand", what is the difference between them? For my trying, the "read_strand" is all t in the output file, is it something that I missed?

**Comment by PengNi** [comment]
Hi @zcWang0591, `read_strand` is a legacy feature for R9 2D reads. An R9 2D read has a template sequence and a complement sequence. However R9 2D technique is no longer used by Nanopore. 1D reads only have a sequence in template strand.

Best,
Peng

**Comment by zcWang0591** [comment]
Thank you! It is clear now.

**Comment by zcWang0591** [comment]
Hi, I still have a little problem that if I want to train a model for my experiment data, the features extracted by Deepsignal include read_strand, which is designed for R9 2D technique, but my experiment uses 1D technique, so does it influence the downstream process? Or I just ignore it？

**Comment by PengNi** [comment]
@zcWang0591 ，yes, you can just ignore it.

**Comment by zcWang0591** [comment]
OK, thank you
