### ISSUE TITLE
Expected results for example data set?

### ISSUE THREAD

**Issue by eexwhyzee** [bioinfomaticsCSU/deepsignal#5]
Hi,

Running deepsignal locally, i used the example data/model located [here](https://people.cs.clemson.edu/~luofeng/deepsignal/) and getting these results:
![screen shot 2019-02-21 at 12 36 32 pm](https://user-images.githubusercontent.com/13672394/53200177-c02d2100-35d5-11e9-9ec1-365e6fcb3aa9.png)

and I was wondering if the accuracy is supposed to be this low for the example dataset?

**Comment by PengNi** [comment]
Hi @eexwhyzee ,

Sorry for the delay. The results may be a little bit misleading. During the mods-calling, deepsignal takes all samples as unmethylated (_i.e._ the True labels of all samples are 0) by default when calculating the accuracy. This is not the truth for the example data. Beacuse the example data is sequenced from a native sample.

Also, the accuracy is just for an estimation,  it won't effect the prediction results.

We are considering change the example data soon, and revise the code for stdout too.

Best,
Peng

**Comment by eexwhyzee** [comment]
Thanks for the reply @PengNi! btw great work so far!
