### ISSUE TITLE
Question about train dataset

### ISSUE THREAD

**Issue by zcWang0591** [bioinfomaticsCSU/deepsignal#50]
Hi, 
I have a question about your train dataset. In the previous question, you suggest that other public dataset can be used for training.(https://github.com/bioinfomaticsCSU/deepsignal/issues/7#issuecomment-511727655)
My question is that do these datasets need base-calling first? Or I just start from tombe re-squiggle step? And for the experiment data generated by myself, maybe I need to do the base-calling before using tombo? And can I use Guppy rather than Albacore? Can DeepSignal use the base-calling result of Guppy?
Many thanks.

**Comment by PengNi** [comment]
Hi @zcWang0591 , to train or test, the raw reads always need to be basecalled first and then re-squiggled. For the methioned datasets, I suggest that you can use the NA12878 and HX1 R9.4 reads to do some tests. You can either use their basecalling results or basecall by yourself.

In our tests, Guppy is also compatible with the DeepSignal model.

Best,
Peng

**Comment by zcWang0591** [comment]
Thank you for reply, one more question is that I see the help document about extract features, and it seems that it has an argument about methy_label. So, maybe in one feature extract process, it can only solve one methy_label(just methy/unmethy)? 
So, should I do the feature extract process separately for methy/unmethy data? And, can the results of feature extract process in the pipeline directly be used for training?
Many thanks.

**Comment by PengNi** [comment]
@zcWang0591 , 1) yes, in one extract process, the samples of only one label are extracted. 2) the results of extract process can not used for traninig directly. First, in extract process, you can use `--positions` to extract samples of only highly methylated/unmethylated sites. Second, the samples of methylated and ummethylated sites should be shuffled and concated ([concat_two_files.py](https://github.com/bioinfomaticsCSU/deepsignal/blob/master/scripts/concat_two_files.py) may be helpful.), and then splited to train and valid file. 

You can also check other issues about extract and training.

Best,
Peng

**Comment by zcWang0591** [comment]
Thank you. I will try your suggestions.

**Comment by zcWang0591** [comment]
Hi, I have a small question about training, does Deepsignal support multi-gpu for training. I have read the supplementary materials of your paper, it seems that deepsignal can use multi-gpu？ So, is there any difference between single-gpu and multi-gpu? Many thanks.

**Comment by PengNi** [comment]
@zcWang0591 , sorry, deepsignal does not support multi-gpu.
