### ISSUE TITLE
Example training and validation data

### ISSUE THREAD

**Issue by akk01** [bioinfomaticsCSU/deepsignal#53]
Can you also put example training and validation data, which will be really helpful in understanding input file.

**Comment by PengNi** [comment]
Hi @akk01 , to train a model, #13 , #10 , #7 , #32 and #50 would be heplful. 
The format of training and validation file is as the uploaded file. 
[human.albacore.pass.tem.CpG.signal_features.bn17_sn360.train.sample.txt](https://github.com/bioinfomaticsCSU/deepsignal/files/5147907/human.albacore.pass.tem.CpG.signal_features.bn17_sn360.train.sample.txt)

Thanks for your interest of deepsignal.

Best,
Peng

**Comment by akk01** [comment]
Great! Thanks a lot.

**Comment by akk01** [comment]
Hi Peng, currently DeepSignal accepts a specific input format for training and validation, which are generated by `deepsignal extract`. I am interested in using DeepSignal for my dataset, which is NxN numeric table and  has two targets - modified site or 1 and unmodified sites or 0. Please advise me.

**Comment by akk01** [comment]
> Hi @akk01 , to train a model, #13 , #10 , #7 , #32 and #50 would be heplful.
> The format of training and validation file is as the uploaded file.
> [human.albacore.pass.tem.CpG.signal_features.bn17_sn360.train.sample.txt](https://github.com/bioinfomaticsCSU/deepsignal/files/5147907/human.albacore.pass.tem.CpG.signal_features.bn17_sn360.train.sample.txt)
> 
> Thanks for your interest of deepsignal.
> 
> Best,
> Peng

I didn;t quite get  #13 , #10 , #7 , #32 and #50. What are these numbers?

**Comment by PengNi** [comment]
@akk01 , sorry, I don't quite understand what a NxN table means. 

If you have features in different format, the architeture of the DNN model may need to be changed too,

Best,
Peng

**Comment by akk01** [comment]
![Screen Shot 2020-09-03 at 2 14 16 PM](https://user-images.githubusercontent.com/25061318/92151850-c9fd2a80-edef-11ea-96f7-31ea7929d985.png)
This a dummy data format for which I want to use DeepSignal.

**Comment by PengNi** [comment]
Hi @akk01 , DeepSignal doesn't accept your data format. It seems that there are only sequence features in your data. I suggest that you design a new DNN model for your data.

Best,
Peng
