### ISSUE TITLE
Albacore paramter used for basecalling

### ISSUE THREAD

**Issue by akk01** [bioinfomaticsCSU/deepsignal#54]
Hi,

For my practice, I downloaded two human Fast5: (1) `NA12878.native.simpson.101515` (2) `NA12878.native.simpson.103015` from `https://www.ebi.ac.uk/ena/browser/view/PRJEB13021`. These data were processed with DeepSignal in your paper.

The very first step of DeepSingal is to perform basecalling with Albacore. I performed basecalling with Albacore v2.3.4, which didn't generate any fastq. 

Do you know the Albacore parameters such as 	`--flowcell` and `--kit` that you used. I may have been using wrong Albacoere version and paramters.

**Comment by PengNi** [comment]
Hi @akk01 ,

The `NA12878.native.simpson.101515` and `NA12878.native.simpson.103015` is sequenced by R7 2D tech, which has been deprecated by ONT. I suggest that you use NA12878/HX1 R9.4 reads (#44 , [NA12878](https://github.com/nanopore-wgs-consortium/NA12878/blob/master/Genome.md), #42 , [HX1](http://hx1.wglab.org/)) for practice.

Best,
Peng

**Comment by akk01** [comment]
Very helpful. Thanks for the clarification.
