### ISSUE TITLE
Information about deepsignal

### ISSUE THREAD

**Issue by lucio-cyber** [bioinfomaticsCSU/deepsignal#56]
Hi, I'm Lucio, I would like some more information about this tool and therefore I would like to ask you:
1- what are the differences between extract features and call mods;
2- launching deepsignal as I can see when the tool ends and how long it takes
3- in extract features you can change the value of - -write-path or the one present is standard / default
4- in call modification you can change the value of - - model_path

**Comment by PengNi** [comment]
Hi Lucio,

Thanks for your interest.

1. `extract` extracts features to text for training models or calling methylation. `call_mods` calls methylation from fast5s or the text file generated by `extract`.
2. Currently deepsignal doesn't support estimating the progress in real-time. We may implement this further.
3. `--write-path` can be changed to the path/file name whatever you want to.
4. `--model_path` must be set to the file path of the model. You can download the model from [google drive](https://drive.google.com/drive/folders/1zkK8Q1gyfviWWnXUBMcIwEDw3SocJg7P?usp=drive_open). After uncompress it, the model can be used for `call_mods`:
```shell
deepsignal call_mods --input_path fast5s.al/ --model_path model.CpG.R9.4_1D.human_hx1.bn17.sn360.v0.1.7+/bn_17.sn_360.epoch_9.ckpt --result_file fast5s.al.CpG.call_mods.tsv --reference_path GCF_000146045.2_R64_genomic.fna --corrected_group RawGenomeCorrected_001 --nproc 10 --is_gpu no
```

Best,
Peng

**Comment by lucio-cyber** [comment]
So if I don't download this model I can't recall the changes? This model is very large, how much memory does it take up?
Then I have another question:
1- I launched the feature extraction, I can't understand when the tool ends. Also he tells me “write_process started”

**Comment by PengNi** [comment]
Hi Lucio,

The model takes 8G-11G GPU RAM.
1- `write_process started..` means the `extract` process just starts. deepsignal can't estimate when the process ends.
2- You can check README for the illustration of trained models. `model.CpG.R9.4_1D.human_hx1.bn17.sn360.v0.1.7+.tar.gz` is our latest model for 5mCpG detection.

Best,
Peng

**Comment by lucio-cyber** [comment]
Hi Peng, 
but does the model occupy 8G-11G once unzipped?
How much does the compressed one take roughly?
Best Regards,
Lucio

**Comment by PengNi** [comment]
~500M disk space after unzipped.

**Comment by lucio-cyber** [comment]
So compressed is 500 Megabytes, decompressed 8-11 Gigabytes. Did I get it right ?

**Comment by PengNi** [comment]
Not actually. The model takes ~500M space in disk after unzipped, and takes 8-11G RAM in GPU when calling methyaltion.

**Comment by lucio-cyber** [comment]
But before decompression how much does it take up both on disk and on RAM ?

**Comment by PengNi** [comment]
The model can't be loaded to GPU memory without unzipping it.

**Comment by lucio-cyber** [comment]
And to disk ?

**Comment by PengNi** [comment]
Sorry, I cannot understand what you mean. The model tar.gz file is already in disk when you download it. It has to be unzipped and load to GPU for methylation calling.

**Comment by lucio-cyber** [comment]
What I ask is: when I download the tar.gz file of the model how much does it occupy on disk?

**Comment by PengNi** [comment]
187M, the size of file can be checked in google drive.

**Comment by lucio-cyber** [comment]
Ok! Thank you so much for helping me!
Best Regards,
Lucio

**Comment by lucio-cyber** [comment]
Hi Peng,
I unzipped the model and it gives me a folder inside which it gives me 'bn_17.sn_360.epoch_9.ckpt.index' and 'bn_17.sn_360.epoch_9.ckpt.meta' but in the command instructions it is marked only '- model_path model.CpG.R9.4_1D.human_hx1.bn17.sn360.v0.1.7 + / bn_17.sn_360.epoch_9.ckpt '.
My question is : do I just enter 'model ..... ckpt' or do I enter 'model .... ckpt.index' or 'model .... ckpt.meta' ?
I thought of inserting 'model ... ckpt.index', I think it's the right one, can you confirm?

**Comment by PengNi** [comment]
Hi Lucio,

Please refer to #11 .

Best,
Peng
