### ISSUE TITLE
The feature extraction output 'signal_means' are different from the value in fast5 files.

### ISSUE THREAD

**Issue by LongxianChen** [bioinfomaticsCSU/deepsignal#58]
PengNi老师：
您好！我使用deepsignal extract命令提取feature，使用参数--corrected-group RawGenomeCorrected_001，输出结果后发现'signal_means'那一列的数值与fast5文件中RawGenomeCorrected_001/BaseCalled_template/Events/norm_mean的相应位点的数值是不同的。按照我的理解，这两个位置的数值应该是一致的，是我理解错了吗？还是我在使用时软件的某些参数没设置好导致了这种情况？麻烦您帮忙解答一下，谢谢！
------
Dear Ni:
I used 'deepsignal extract' command to extract my features with the option '--corrected-group RawGenomeCorrected_001', but I found that the value of 'signal means' column is different from the corresponding values in  RawGenomeCorrected_001/BaseCalled_template/Events/norm_mean. In my opinion, the values should be the same, right? Or maybe I set the wrong options? Could you tell me the reason? Thanks!

**Comment by PengNi** [comment]
Hi @LongxianChen ,

We didn't use values form event table. Instead, we use the raw signals (with pA convertion) of each base to calculate mean/std. So they are different.

Best,
Peng
