### ISSUE TITLE
defining methyl_label

### ISSUE THREAD

**Issue by akk01** [bioinfomaticsCSU/deepsignal#59]
I am wondering how `extract_features.py` defines `methyl_label` as 0 or 1. Do you calculate it based on signal or its defined by Tombo when you process hd5 file.

**Comment by PengNi** [comment]
Hi,

  `--methy_label` is a param for training which is used together with `--positions`  to extract high confidence (un)methylated samples. If `--positions` are methylated sites, then `--methy_label` should be set to 1, and vice versa.
  
  It can be ignored when calling methylation.

Best,
Peng
