### ISSUE TITLE
Error while running call mods using GATC model

### ISSUE THREAD

**Issue by onkar2470** [bioinfomaticsCSU/deepsignal#60]
Hi, 
I am running deepsignal call mods for my data.
For 5mC it ran perfectly without any error.
But for 6mA, I downloaded model file from drive and while running deepsignal call mods it is showing error.
This error seems to be related to model file.

### NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key modelem/bw/multi_rnn_cell/cell_0/lstm_cell/bias not found in checkpoint
	 [[node save/RestoreV2 (defined at /home/envs/deepsignal/lib/python3.6/site-packages/deepsignal/call_modifications.py:212) ]]

finishing the write_process..
0 of 1621559 fast5 files failed..
call_mods costs 60.83 seconds..
Traceback (most recent call last):
  File "/home/.local/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/home/.local/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/.local/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/.local/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

This is the pip list output:
Package              Version   
-------------------- ----------
absl-py              0.10.0    
appdirs              1.4.3     
astor                0.8.1     
CacheControl         0.12.6    
certifi              2019.11.28
chardet              3.0.4     
colorama             0.4.3     
contextlib2          0.6.0     
Cython               0.29.21   
deepsignal           0.1.7     
distlib              0.3.0     
distro               1.4.0     
future               0.18.2    
gast                 0.4.0     
grpcio               1.32.0    
h5py                 2.10.0    
html5lib             1.0.1     
idna                 2.8       
importlib-metadata   1.7.0     
ipaddr               2.2.0     
Jinja2               2.11.2    
joblib               0.16.0    
Keras-Applications   1.0.8     
Keras-Preprocessing  1.1.2     
lockfile             0.12.2    
mappy                2.17      
Markdown             3.2.2     
MarkupSafe           1.1.1     
mock                 4.0.2     
msgpack              0.6.2     
numpy                1.19.2    
ont-fast5-api        3.1.6     
ont-tombo            1.5.1     
packaging            20.3      
pandas               1.1.2     
patsy                0.5.1     
pep517               0.8.2     
pip                  20.0.2    
pkg-resources        0.0.0     
progress             1.5       
progressbar33        2.4       
protobuf             3.13.0    
pyfaidx              0.5.9.1   
pyparsing            2.4.6     
python-dateutil      2.8.1     
pytoml               0.1.21    
pytz                 2020.1    
requests             2.22.0    
retrying             1.3.3     
rpy2                 2.9.5     
scikit-learn         0.23.2    
scipy                1.5.2     
setuptools           50.3.0    
six                  1.14.0    
statsmodels          0.12.0    
tensorboard          1.13.1    
tensorflow           1.13.1    
tensorflow-estimator 1.13.0    
termcolor            1.1.0     
threadpoolctl        2.1.0     
tqdm                 4.49.0    
urllib3              1.25.8    
webencodings         0.5.1     
Werkzeug             1.0.1     
wheel                0.34.2    
zipp                 3.1.0     

Earlier also i have used deepsignal for 6mA with same model, but was not getting any error.
This time only having this problem.
Waiting for reply.
Thank you,

**Comment by PengNi** [comment]
Hi @onkar2470 , sorry for the confusing. We updated the human_CpG model at the same time when we updated deepsignal  to `0.1.7`. However, we did not update the GATC model. The GATC model is only compatible with deepsignal<=`0.1.6`.

Best,
Peng

**Comment by onkar2470** [comment]
Thanx PengNi,
