### ISSUE TITLE
ModuleNotFoundError: No module named 'txt_formater'

### ISSUE THREAD

**Issue by PanZiwei** [bioinfomaticsCSU/deepsignal#62]
Hi,
I am trying to calculate methylation frequencies using [scripts/call_modification_frequency.py](https://github.com/bioinfomaticsCSU/deepsignal/blob/master/scripts/call_modification_frequency.py), but get the error below:
```
Traceback (most recent call last):
  File "cal_methylation_freq.py", line 11, in <module>
    from txt_formater import ModRecord
ModuleNotFoundError: No module named 'txt_formater'
Traceback (most recent call last):
  File "cal_methylation_freq.py", line 11, in <module>
    from txt_formater import ModRecord
ModuleNotFoundError: No module named 'txt_formater'
```

I didn't find any information about the `txt_formater` module or find the download link for the package online. But I found the [script](https://github.com/bioinfomaticsCSU/deepsignal/blob/b488b5ba9b77d1c99707071b2b6e9341e2b6f82a/scripts/txt_formater.py#L8) in the script folder. Instead of cloning the git link, I installed the Deepsignal by `conda install deepsignal`. In this case, does it mean that I have to download both `call_modification_frequency.py` and `txt_formater.py` to use calculate methylation frequencies function?

Thank you so much for your help!

**Comment by PengNi** [comment]
@PanZiwei ，yes, the two scripts must be put to the same directory.
