### ISSUE TITLE
Available trained model on E.coli data?

### ISSUE THREAD

**Issue by Lamicc** [bioinfomaticsCSU/deepsignal#63]
Hi there,

I wonder if it is possible to get a trained model on E.coli CpG methylation data anywhere?

Thanks in advance!

**Comment by PengNi** [comment]
Hi @Lamicc ,

Thanks for your interest of our work. I 'm sorry that our _E. coli_ model were removed in our server and we didn't save a copy of the model. However, the model were trained by using _E. coli_ R9 2D data, and it is out of date, as the most used pore chemistries of nanopore are R9.4.1, R9.5 and R10.3 now.

Best,
Peng

**Comment by Lamicc** [comment]
Thank you, Peng.
