### ISSUE TITLE
guppy_basecaller in README.md instructions

### ISSUE THREAD

**Issue by kxk302** [bioinfomaticsCSU/deepsignal#65]
Hello,
I am trying to follow the instructions in README.md file, but do not see any instructions on how to install guppy_basecaller. Could you please advise how to install guppy_basecaller? 
Many thanks!

**Comment by PengNi** [comment]
Hi @kxk302 , Guppy is not an open-source software and is only available in [Nanopore Community](https://nanoporetech.com/community). So we did not put the instructions of Guppy. If you can't access [Nanopore Community](https://nanoporetech.com/community), you can use [Bonito](https://github.com/nanoporetech/bonito) instead.

Best,
Peng

**Comment by kxk302** [comment]
Thank you for clarification @PengNi, appreciate it.
