### ISSUE TITLE
Using multiple fast5 dirs

### ISSUE THREAD

**Issue by u2progress** [bioinfomaticsCSU/deepsignal#66]
Hello,

I have two single fast5 directories (from two Nanopore runs for the same sample) that I have resquiggled using Tombo in the past. Is it possible to give deepsignal two dirs to call modifications from? I ask since the Tombo index files are separate for each of the directories, so in order to merge them I would have to run resquiggle again if I understand correctly. 

Thank you.

**Comment by PengNi** [comment]
Hi @u2progress , deepsignal doesn't support multi dirs as input at present. deepsignal doesn't need tombo index files either. So you can call the two dirs seperately, without resquiggle them again.

Best,
Peng

**Comment by u2progress** [comment]
Thanks for your swift reply @PengNi !
Since these runs are for the same genome and sample, I wanted to get modifications utilising the entire dataset and coverage. 
If tombo index isn't required, I could move the two fast5 dirs into a single one for the purpose of running deepsignal since it searches recursively. Is that right?

**Comment by PengNi** [comment]
Yes, the two dirs can be moved into one.

Best,
Peng

**Comment by u2progress** [comment]
Perfect, thank you again.
