### ISSUE TITLE
Updating DeepSignal? [question]

### ISSUE THREAD

**Issue by davidebolo1993** [bioinfomaticsCSU/deepsignal#68]
Hi @PengNi,

thanks a lot for building this great tool. Just a quick question. Is there any chance that DeepSignal can be updated to work with more recent versions of tensorflow? Many modules have changed since tensorflow 1.13.1 and it would be nice if DeepSignal could work outside its own environment, especially if this has to be used in combination with other tools requiring up-to-date modules from tensorflow.

**Comment by PengNi** [comment]
Hi @davidebolo1993 , thanks for your interest of deepsignal. Actually I have re-written deepsignal to deepsignal2, in which I used PyTorch instead of tensorflow. But I haven't done training a new human-cpg model of deepsignal2 yet. It may still need one month or so. 

So since I may not get time to update the tensorflow version, does a pytorch version (>=1.2.0) of deepsignal work for you?

Best,
Peng

**Comment by davidebolo1993** [comment]
Hi @PengNi, 

no need to hurry at all, I think I can wait ~1 month to have the new version (and the first version works fine, although it throws a lot of warnings due to the outdated libraries). This was just to ask if a new release has been somehow scheduled. I'm also happy to test the developmental version by myself if this can help.
Thanks,

Davide

**Comment by PengNi** [comment]
Hi @davidebolo1993 ,

We just released new version of deepsignal (see [deepsignal2](https://github.com/PengNi/deepsignal2)) with a newly pre-trained 5mCpG model. Please check it if it can help. Thank you!

Best,
Peng

**Comment by davidebolo1993** [comment]
Hi @PengNi,

thanks a lot. I mainly use DeepSignal to call methylation at human CGs . Would you suggest to switch to DeepSignal2 to this purpose?

Best,
Davide

**Comment by davidebolo1993** [comment]
I've just re-tested DeepSignal2 on some old dataset that I previously analyzed with DeepSignal and I can say that results are comparable. Thanks a lot ! Any plan to make DeepSignal Tombo-independent? I would say that pre-processing is the bottleneck in terms of speed.

Thanks, 

Davide

**Comment by PengNi** [comment]
@davidebolo1993 , thanks for your test and suggestion! We tried before to re-write the tombo part, or change tombo with other similar tools. However, I'd say tombo is still the best choice for deepsignal now, even it is slow.

Best,
Peng

**Comment by davidebolo1993** [comment]
Thanks !

Best,

Davide
