### ISSUE TITLE
What's the difference between the CpG model and the GATC model?

### ISSUE THREAD

**Issue by 123chenshixin** [bioinfomaticsCSU/deepsignal#69]
Hi @PengNi,

I just want to enquiry the difference between the CpG model and the GATC model. Does the CpG model indicate that can detect 5mC methylation of the DNA and the GATC model is 6mA ? Because I am eager to detect both 5mC and 6mA methylation for my owned assembling bacterical genomes.

**Comment by PengNi** [comment]
Hi @123chenshixin ,

Thanks for your interests of deepsignal. Yes, CpG model is for 5mC detection in CpGs and GATC model is for 6mA detection in GATCs.

However, the GATC model may be out of date now, cause it is trained by R9 2D reads, which has been decrepted by ONT. So, besides using deepsignal, I suggest that you try another tool (megolodon+rerio models) for you data, too.

Best,
Peng
