### ISSUE TITLE
Where does deepsignal save the temporary files?

### ISSUE THREAD

**Issue by ViHammer** [bioinfomaticsCSU/deepsignal#71]
How does deepsignal save the temporary results? Ram usage suggests that temporary files are created somewhere, but I cannot find them.
Cause of my question is the "disappearance" of the output file of my last run. A test run with a reduced dataset was successful, but I could not find the output file of my completed run. The path to my result-file was correct and deepsignal did not produce an error message. I am wondering if a cronjob deleted some temp files. Or can relative paths cause issues?

Thanks in advance!

**Comment by PengNi** [comment]
Hi @ViHammer , thanks for your interest of deepsignal. Does `temporary results` mean the `--result_file` param in `deepsignal call_mods` command? And, can you show me the command you used and the log of your run?

Best,
Peng

**Comment by ViHammer** [comment]
I think my problem solved itself. On my first run, no `result_file` was created. I thought this was normal behavior and that it would only create this file once all positions had been called. This is why I was wondering where deepsignal created temporary files.
I restarted deepsignal, and it seems to work correctly now.

Thanks for the rapid response!
