### ISSUE TITLE
unsuccessfully processed reads

### ISSUE THREAD

**Issue by xj-Liang-Olga** [bioinfomaticsCSU/deepsignal#73]
Hi, 
I would like to ask how to eliminate the unsuccessful reads processed by Tombo in subsequent analysis if they are not used.

Thanks for your reply.

**Comment by PengNi** [comment]
@Xiaojuan-Liang , thanks for your interest. The unsuccessful reads don't need to be taken extra care. Those reads can be recognized as 'failed reads' automaticlly by deepsignal.

Best,
Peng
