### ISSUE TITLE
Questions about sequence module

### ISSUE THREAD

**Issue by Flower9618** [bioinfomaticsCSU/deepsignal#77]
Hi. Happy new year! Thank you very much for sharing this excellent tool. 
I would like to know how do you transfer the sequence context into the fourth feature in the sequence module, is it a relationship like {A:0; T:1; C:2; G:3} ?

**Comment by PengNi** [comment]
@Flower9618 , yes, I transfer ACGT to 0123, then transfer the sequence of 0123 to higher dimension using embeding.
