### ISSUE TITLE
Training of a custom model

### ISSUE THREAD

**Issue by hukai916** [bioinfomaticsCSU/deepsignal#79]
Hi developers,

Thanks for creating DeepSignal!

For my data, the modified bases don't appear in specific motifs, instead, we have collected ground truth information, can I still use DeepSignal to train a model while leveraging the ground truth information?

Best,

--Kai

**Comment by PengNi** [comment]
Hi @hukai916 , basicly A new deepsignal model can be trained as long as we have positive samples and negative samples. However, without specific motifs (say we set --motifs as N), the performance may be not guaranteed.

**Comment by hukai916** [comment]
Thanks for your quick reply! 

Though performance is not guaranteed, I am still interested in testing it out. Seems that the `training model` part of the documentation is minimal, I also looked at `deepsignal train -h`, however, it is still quite hard for me to move forward, I encountered the following headaches:
1. Where is extract_features.py? I saw it is inside deepsignal_plant repo? Is there any usage documentation of it?
2. What are positive and negative samples? How to prepare and shuffle? Do you have some example?

It will make my easier it you can supply some step-by-step tutorial on the model training.

Again, thanks for creating deepsignal, it is awesome!

**Comment by PengNi** [comment]
Hi @hukai916 , you can check previous issues (like #74, #53  ) for more information.

Best,
Peng

**Comment by hukai916** [comment]
Hi Peng, 

This is very informative, I highly recommend adding them into the documentation. 

I will let you if I run into other problems. Thanks again!

--Kai
